# Generated by Django 4.1.5 on 2023-02-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='duration',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
